formatter: "markdown table" # required

version: ">= 0.13.0"

content: |-
  {{ if eq .Module.Header "validate.tf" }}
    ## Usage
    This file is used for validating the following modules: {{.Config.ModuleRoot}}

    {{ .Modules }}
  {{ else }}
    {{ .Module.Header }}
    {{ .Requirements }}

    ## Usage
    Basic usage of this module is as follows:
    ```hcl
      module "example" {
        {{"  "}} source = "<module-path>"
        {{- if .Module.RequiredInputs }}
        {{"\n "}} # Required variables
        {{- range .Module.RequiredInputs }}
        {{"  "}} {{ .Name }} = {{ .GetValue }}
        {{- end }}
        {{- end }}
        {{- if .Module.OptionalInputs }}
        {{"\n "}}  # Optional variables
        {{- range .Module.OptionalInputs }}
        {{"  "}} {{ .Name }} = {{ .GetValue | printf "%s" }}
        {{- end }}
        {{- end }}
      }
    ```

    {{ .Providers }}

    {{ .Resources }}

    {{ .Modules }}

    {{ .Inputs }}

    {{ .Outputs }}
  {{ end }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
