formatter: "markdown table" # this is required

version: ">= 0.13.0"

content: |-
  {{ .Requirements }}

  ## Usage
  Basic usage of this module is as follows:
  ```hcl
    module "example" {
      {{"\s\s"}} source  = "<module-path>"
  {{- if .Module.RequiredInputs }}
      {{"\n\s\s"}} # Required variables
      {{- range .Module.RequiredInputs }}
      {{"\s\s"}} {{ .Name }}  = {{ .GetValue }}
      {{- end }}
      {{- end }}
  {{- if .Module.OptionalInputs }}
      {{"\n\s\s"}} # Optional variables
      {{- range .Module.OptionalInputs }}
      {{"\s\s"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
      {{- end }}
      {{- end }}
    }
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
