name: Destroy

on:
  workflow_dispatch:
    inputs:
      root_module:
        type: choice
        options:
          - 'environments/development'
          - 'environments/staging'
          - 'environments/production'
        required: true
        description: "The root module to deploy."
      noop:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
        required: true
        description: "Noop (no operations) mode."

concurrency:
  group: ${{ github.workflow }}-${{ github.event }}
  cancel-in-progress: true

env:
  ROOT_MODULE_DIRECTORY: terraform/${{ github.event.inputs.root_module }}

jobs:
  # Require approval in the form of an open issue in order to destroy the infrastructure.
  approve-teardown:
    name: Approve Infrastructure Teardown
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: user1,use2,...,userN
          minimum-approvals: 1,2,...,N
          issue-title: "Approve infrastructure teardown for ${{ github.event.inputs.root_module }}." 
          exclude-workflow-initiator-as-approver: false

  terraform_destroy:
    name: Destroy Infrastructure
    if: github.ref == 'refs/heads/main'
    needs: approve-teardown
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.8, < 2.0"

      - name: Terraform init
        run: terraform init
        working-directory: $ROOT_MODULE_DIRECTORY

      - name: Terraform plan
        run: terraform plan -destroy -out=tfplan -input=false
        working-directory: $ROOT_MODULE_DIRECTORY

      - name: Terraform apply
        if: github.event.inputs.noop == 'false'
        run: terraform apply tfplan
        working-directory: $ROOT_MODULE_DIRECTORY
