# This workflow requires an approval and based on that destroys our infrastructure.
name: destroy
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Specify the environment to be destroyed"

jobs:
  approve:
    name: approve-infra-teardown
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.8.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: christosgalano
          minimum-approvals: 1
          issue-title: "Approve infrastructure teardown for the ${{ inputs.environment }} environment"
          exclude-workflow-initiator-as-approver: false

  destroy:
    name: destroy
    needs: approve
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/terraform/environments/${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: |
          terraform apply -destroy -no-color -auto-approve \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="tenant_id=${{ secrets.TENANT_ID }}" \
            -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
