# This workflow generates Terraform documentation for the modules included in the repository.
name: generate-terraform-docs
run-name: ${{ github.workflow }}
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: "Ref to pull from and push to"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TERRAFORM_DIR: ${{ github.workspace }}/terraform

jobs:
  # Generate Terraform documentation for each module.
  generate-terraform-docs:
    name: generate-terraform-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout - branch
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v3

      - name: Checkout - pull request
        if: github.event_name == 'deploy' # same as the caller workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Generate Terraform documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: ${{ env.TERRAFORM_DIR }}/
          config-file: .terraform-docs.yaml
          output-method: replace
          git-push: "true"
