name: generate-terraform-docs
run-name: ${{ github.workflow }}
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

env:
  TERRAFORM_DIR: ${{ github.workspace }}/terraform

jobs:
  generate-terraform-docs:
    name: generate-terraform-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Terraform documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: ${{ env.TERRAFORM_DIR }}/
          args: "--config ${{ env.TERRAFORM_DIR }}/.terraform-docs.yaml"
          git-push: "true"
