name: generate-terraform-docs
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  generate-tf-docs:
    name: generate-tf-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Terraform docs
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_find_dir: ${{ github.workspace }}/terraform
          tf_docs_output_file: README.md
          tf_docs_output_method: replace
          tf_docs_git_push: "true"
