# This workflow generates Terraform documentation for the modules included in the repository.
name: generate-terraform-docs
run-name: ${{ github.workflow }}
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TERRAFORM_DIR: ${{ github.workspace }}/terraform

jobs:
  # Generate Terraform documentation for each module.
  generate-terraform-docs:
    name: generate-terraform-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Two cases based on triggers:
          # - on workflow_call it inherits the ref from the caller workflow
          # - on workflow_dispatch it falls back to the default value (the branch)
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: ${{ env.TERRAFORM_ABS_DIR }}/
          config-file: .terraform-docs.yaml
          output-method: replace
          git-push: "true"
