name: generate-terraform-docs
run-name: ${{ github.workflow }}
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

env:
  TERRAFORM_DIR: ${{ github.workspace }}/terraform

jobs:
  generate-terraform-docs:
    name: generate-terraform-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Terraform modules documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ env.TERRAFORM_DIR }}/
          recursive: true
          recursive-path: modules
          config-file: ".terraform-docs.yml"
          git-push: "true"

      - name: Generate Terraform environments documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ env.TERRAFORM_DIR }}/
          recursive: true
          recursive-path: environments
          config-file: ".terraform-docs.yml"
          git-push: "true"
