name: test
run-name: ${{ github.workflow }}
on:
  push:
    branches:
      - main
    paths:
      - terraform/**

env:
  WORKING_DIR: ${{ github.workspace }}/terraform

jobs:
  filter:
    name: filter-environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select-environment.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find which environment/s changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            modules:
              - '**/modules/**'
            development:
              - '**/development/**'
            staging:
              - '**/staging/**'
            production:
              - '**/production/**'

      # Deployments to multiple environments simultaneously is not allowed.
      # The deployment priority is as follows:
      # 1. Changes to production            files  ->  deploy to production
      # 2. Changes to staging               files  ->  deploy to staging
      # 3. Changes to development or module files  ->  deploy to development
      - name: Select deployment environment
        id: select-environment
        run: |
          environment=""
          if [ "${{ steps.filter.outputs.production }}" == "true" ]; then
            environment="production"
          elif [ "${{ steps.filter.outputs.staging }}" == "true" ]; then
            environment="staging"
          elif [ "${{ steps.filter.outputs.development }}" == "true" ] || [ "${{ steps.filter.outputs.production }}" == "true" ]; then
            environment="development"
          else
            echo "Error finding changes"
            exit 1
          fi
          echo "Selected the $environment environment" 
          echo "environment=$environment" >> $GITHUB_OUTPUT

  deploy:
    name: deploy
    needs: filter
    runs-on: ubuntu-latest
    environment: ${{ needs.filter.outputs.environment }}
    steps:
      - run: echo "It worked, deployed to " ${{ needs.filter.outputs.environment }}
